name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: add checkout
              uses: actions/checkout@v6
            - name: welcome message list files and read the README.md
              run: |
                echo "My first Github Action Job"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artifact.
              run: cowsay -f dragon "Run for cover I am dragon rowr...." >> dragon.txt